### PR TITLE
Add note about brew bundle and brew cleanup.

### LINKED ISSUE #7: Building your Brewfile
Hey man.

Looks like a great, insightful fork. Can you make a recommendation on how to build my Brewfile from current settings?

`brew list` outputs just a few casks and a whole ton of formulae.

Thanks and I hope you don't mind the spam.

Mike

### PR DESCRIPTION
**Pull request by MikeiLL**
fixes #7 (so to speak)

### CODE REVIEW

**Comment by jacobwgillespie** [comment]
Awesome, thank you so much!

**Comment by MikeiLL** [comment]
Thank you! I'm so glad I found this. Been struggling with my pyenv and VSC (fingers crossed). Once again, problem leading to growth. Your Brewfile warrants some examination as well. Looks like you have some good stuff in there. I hadn't even thought about installing non-command-line apps with it, let alone the mac-cli tool.

**Comment by jacobwgillespie** [comment]
Nice, yeah my goal at this point is being able to run `./setup` on any fresh machine and have everything installed and configured. It's definitely not covering 100% of everything, there's random things that aren't automated or aren't installed with Brew (maybe just Mimestream), but I'm happy with how things work at this point.

Good luck with pyenv/VSC, the Python dev tool ecosystem can be a beast. :)

**Comment by MikeiLL** [comment]
> Good luck with pyenv/VSC, the Python dev tool ecosystem can be a beast. :)

Thanks for reminding me that I'm not just green... or an idiot.

I see you have Ableton. I do music, too, but am a Logic user. And Native Instruments Reaktor Pro which is really deep.

**Pull request merged**
